### ISSUE TITLE
Electronics Review by Dr. Palmeri

### ISSUE THREAD

**Issue by clarkbulleit** [clarkbulleit/DesignMiniProjectLight#7]
Im sorry I got the schematic for milestone 03 in late. If you have too much to do I understand it you don't provide feedback

**Comment by clarkbulleit** [comment]
Here is the schematic file:
DesignMiniProjectLight/Electronics/Better_Schematic.JPG

And here is the software flow chart:
DesignMiniProjectLight/Software/Software_Flow_Chart.pdf

**Comment by mlp6** [comment]
Looks like it is coming together!!
